### ISSUE TITLE
Move to JuliaGeo?

### ISSUE THREAD

**Issue by yeesian** [MaximeBouton/LibSpatialIndexBuilder#3]
Following the discussion in https://github.com/yeesian/LibSpatialIndex.jl/pull/4#issuecomment-437201359, might you be interested in moving this package to the JuliaGeo organization where we also maintain binary builders for PROJ and GEOS and GDAL?

**Comment by MaximeBouton** [comment]
Yes of course! Should I just transfer ownership?

**Comment by yeesian** [comment]
I think so, but I'll let @visr confirm to be sure

**Comment by visr** [comment]
Yeah by all means.

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

@yeesian can you make sure @MaximeBouton has repo creation rights in JuliaGeo?

Btw it might be that the builders will be in a monorepo at some point (https://github.com/JuliaPackaging/Yggdrasil) but for now this makes the most sense.

**Comment by MaximeBouton** [comment]
Sounds good. 
So that we don't forget I will write here the few steps that will be needed:
- [ ] transfer ownership to JuliaGeo 
- [ ] update the URL in build.jl in LibSpatialIndex.jl 

I am unsure if we will have to regenerate the binaries or just changing the URL will work but this is not hard to do if needed.

**Comment by visr** [comment]
From when I transferred the builders I didn't have to regenerate anything. Just updating some URLs (though even they forward).

**Comment by MaximeBouton** [comment]
It still says I don't have permission to create repositories

**Comment by yeesian** [comment]
Can you give it a shot again? Thanks!

**Comment by MaximeBouton** [comment]
It worked!
